# Smoke test script for depguard (PowerShell)
# Generated by: cargo xtask generate-smoke
# Generated at: 2026-03-01T04:47:08Z
#
# This script verifies the depguard binary works with basic operations.
# Exit codes: 0 = pass, 1 = fail

param(
    [string]$DepguardBin = ""
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Get-Item "$ScriptDir\..\..").FullName

if ([string]::IsNullOrEmpty($DepguardBin)) {
    $DepguardBin = Join-Path $RepoRoot "target\debug\depguard.exe"
}

function Write-Pass($message) {
    Write-Host "✓ $message" -ForegroundColor Green
}

function Write-Fail($message) {
    Write-Host "✗ $message" -ForegroundColor Red
    exit 1
}

function Write-Info($message) {
    Write-Host "ℹ $message" -ForegroundColor Yellow
}

# Check binary exists
if (-not (Test-Path $DepguardBin)) {
    Write-Fail "Binary not found: $DepguardBin"
}
Write-Pass "Binary exists: $DepguardBin"

# Test --help
try {
    & $DepguardBin --help | Out-Null
    Write-Pass "depguard --help runs successfully"
} catch {
    Write-Fail "depguard --help failed: $_"
}

# Test --version
try {
    $versionOutput = & $DepguardBin --version 2>&1
    if ($versionOutput -match "depguard") {
        Write-Pass "depguard --version outputs version info: ${($versionOutput -split '`n')[0]}"
    } else {
        Write-Fail "depguard --version output unexpected: $versionOutput"
    }
} catch {
    Write-Fail "depguard --version failed: $_"
}

# Create a minimal test fixture
$TempDir = New-TempDir
try {
    $CargoToml = @"
[package]
name = "smoke-test-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
"@
    Set-Content -Path (Join-Path $TempDir "Cargo.toml") -Value $CargoToml -NoNewline

    # Test check command with minimal fixture
    $ReportOut = Join-Path $TempDir "report.json"
    $exitCode = 0
    try {
        & $DepguardBin --repo-root $TempDir check --report-out $ReportOut 2>&1 | Out-Null
    } catch {
        $exitCode = $_.Exception.HResult
    }
    
    if ($LASTEXITCODE -eq 0) {
        Write-Pass "depguard check runs on minimal fixture"
    } elseif ($LASTEXITCODE -eq 2) {
        Write-Pass "depguard check runs (policy violation exit code 2 is acceptable)"
    } else {
        Write-Fail "depguard check failed with exit code $LASTEXITCODE"
    }

    # Verify report was created
    if (Test-Path $ReportOut) {
        Write-Pass "Report file created: $ReportOut"
        try {
            Get-Content $ReportOut | ConvertFrom-Json | Out-Null
            Write-Pass "Report is valid JSON"
        } catch {
            Write-Fail "Report is not valid JSON: $_"
        }
    } else {
        Write-Info "Report file not created (may be expected for some modes)"
    }

    # Test explain command
    try {
        & $DepguardBin explain no_wildcards | Out-Null
        Write-Pass "depguard explain runs successfully"
    } catch {
        Write-Fail "depguard explain failed: $_"
    }
} finally {
    Remove-Item -Recurse -Force $TempDir -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "All smoke tests passed!" -ForegroundColor Green
exit 0

function New-TempDir {
    $tempPath = [System.IO.Path]::GetTempPath()
    $tempDir = Join-Path $tempPath "depguard-smoke-$(Get-Random)"
    New-Item -ItemType Directory -Path $tempDir | Out-Null
    return $tempDir
}
