#!/usr/bin/env bash
# Comprehensive smoke test script for depguard
# Generated by: cargo xtask generate-smoke
# Generated at: 2026-04-22T12:48:08Z
#
# This script verifies the depguard binary works with comprehensive operations.
# Exit codes: 0 = pass, 1 = fail

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEPGUARD_BIN="${DEPGUARD_BIN:-$REPO_ROOT/target/debug/depguard}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

pass() {
    echo -e "${GREEN}✓${NC} $1"
}

fail() {
    echo -e "${RED}✗${NC} $1"
    exit 1
}

info() {
    echo -e "${YELLOW}ℹ${NC} $1"
}

section() {
    echo -e "${BLUE}=== $1 ===${NC}"
}

# Check binary exists
if [[ ! -x "$DEPGUARD_BIN" ]]; then
    fail "Binary not found or not executable: $DEPGUARD_BIN"
fi
pass "Binary exists: $DEPGUARD_BIN"

# Test --help
if "$DEPGUARD_BIN" --help > /dev/null 2>&1; then
    pass "depguard --help runs successfully"
else
    fail "depguard --help failed"
fi

# Test --version
VERSION_OUTPUT=$("$DEPGUARD_BIN" --version 2>&1) || fail "depguard --version failed"
if [[ "$VERSION_OUTPUT" =~ depguard ]]; then
    pass "depguard --version outputs version info: $(echo "$VERSION_OUTPUT" | head -1)"
else
    fail "depguard --version output unexpected: $VERSION_OUTPUT"
fi

# Create a comprehensive test fixture
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

# Create a fixture with various dependency patterns
cat > "$TEMP_DIR/Cargo.toml" << 'EOF'
[package]
name = "smoke-test-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
tokio = { version = "1.0", features = ["full"] }
regex = "*"

[dev-dependencies]
criterion = "0.5"
EOF

section "Testing basic check command"
REPORT_OUT="$TEMP_DIR/report.json"
if "$DEPGUARD_BIN" --repo-root "$TEMP_DIR" check --report-out "$REPORT_OUT" > /dev/null 2>&1; then
    pass "depguard check runs on fixture"
else
    # Check may exit 2 for policy violations, which is acceptable for smoke test
    EXIT_CODE=$?
    if [[ $EXIT_CODE -eq 2 ]]; then
        pass "depguard check runs (policy violation exit code 2 is acceptable)"
    else
        fail "depguard check failed with exit code $EXIT_CODE"
    fi
fi

# Verify report was created and is valid JSON
if [[ -f "$REPORT_OUT" ]]; then
    pass "Report file created: $REPORT_OUT"
    if command -v jq > /dev/null 2>&1; then
        if jq empty "$REPORT_OUT" 2>/dev/null; then
            pass "Report is valid JSON"
        else
            fail "Report is not valid JSON"
        fi
    else
        info "jq not available, skipping JSON validation"
    fi
else
    fail "Report file not created"
fi

section "Testing output formats"
# Test markdown output
if "$DEPGUARD_BIN" md --report "$REPORT_OUT" > "$TEMP_DIR/output.md" 2>&1; then
    pass "Markdown output generation works"
else
    fail "Markdown output generation failed"
fi

# Test annotations output
if "$DEPGUARD_BIN" annotations --report "$REPORT_OUT" > "$TEMP_DIR/annotations.txt" 2>&1; then
    pass "Annotations output generation works"
else
    fail "Annotations output generation failed"
fi

# Test SARIF output
if "$DEPGUARD_BIN" sarif --report "$REPORT_OUT" > "$TEMP_DIR/output.sarif" 2>&1; then
    pass "SARIF output generation works"
    # Validate SARIF is valid JSON
    if command -v jq > /dev/null 2>&1; then
        if jq empty "$TEMP_DIR/output.sarif" 2>/dev/null; then
            pass "SARIF output is valid JSON"
        else
            fail "SARIF output is not valid JSON"
        fi
    fi
else
    fail "SARIF output generation failed"
fi

# Test JUnit output
if "$DEPGUARD_BIN" junit --report "$REPORT_OUT" > "$TEMP_DIR/output.junit" 2>&1; then
    pass "JUnit output generation works"
else
    fail "JUnit output generation failed"
fi

# Test JSONL output
if "$DEPGUARD_BIN" jsonl --report "$REPORT_OUT" > "$TEMP_DIR/output.jsonl" 2>&1; then
    pass "JSONL output generation works"
else
    fail "JSONL output generation failed"
fi

section "Testing exit codes"
# Test with a clean fixture (should exit 0)
CLEAN_DIR=$(mktemp -d)
cat > "$CLEAN_DIR/Cargo.toml" << 'EOF'
[package]
name = "clean-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
EOF

CLEAN_REPORT="$CLEAN_DIR/report.json"
if "$DEPGUARD_BIN" --repo-root "$CLEAN_DIR" check --report-out "$CLEAN_REPORT" > /dev/null 2>&1; then
    pass "Clean fixture exits with code 0"
else
    EXIT_CODE=$?
    if [[ $EXIT_CODE -eq 0 ]]; then
        pass "Clean fixture exits with code 0"
    else
        fail "Clean fixture exited with code $EXIT_CODE (expected 0)"
    fi
fi
rm -rf "$CLEAN_DIR"

# Test with violations (should exit 2)
VIOLATIONS_DIR=$(mktemp -d)
cat > "$VIOLATIONS_DIR/Cargo.toml" << 'EOF'
[package]
name = "violations-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "*"
tokio = "*"
EOF

VIOLATIONS_REPORT="$VIOLATIONS_DIR/report.json"
if "$DEPGUARD_BIN" --repo-root "$VIOLATIONS_DIR" check --report-out "$VIOLATIONS_REPORT" > /dev/null 2>&1; then
    info "Violations fixture may not trigger violations (depends on config)"
else
    EXIT_CODE=$?
    if [[ $EXIT_CODE -eq 2 ]]; then
        pass "Violations fixture exits with code 2 (policy failure)"
    else
        info "Violations fixture exited with code $EXIT_CODE"
    fi
fi
rm -rf "$VIOLATIONS_DIR"

section "Testing diff-scope functionality"
# Create a workspace for diff-scope testing
WORKSPACE_DIR=$(mktemp -d)
cat > "$WORKSPACE_DIR/Cargo.toml" << 'EOF'
[workspace]
members = ["member1", "member2"]
EOF

mkdir -p "$WORKSPACE_DIR/member1"
cat > "$WORKSPACE_DIR/member1/Cargo.toml" << 'EOF'
[package]
name = "member1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
EOF

mkdir -p "$WORKSPACE_DIR/member2"
cat > "$WORKSPACE_DIR/member2/Cargo.toml" << 'EOF'
[package]
name = "member2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.0"
EOF

DIFF_REPORT="$WORKSPACE_DIR/report.json"
if "$DEPGUARD_BIN" --repo-root "$WORKSPACE_DIR" check --report-out "$DIFF_REPORT" > /dev/null 2>&1; then
    pass "Workspace check with diff-scope works"
else
    EXIT_CODE=$?
    if [[ $EXIT_CODE -eq 0 || $EXIT_CODE -eq 2 ]]; then
        pass "Workspace check with diff-scope works (exit code $EXIT_CODE)"
    else
        fail "Workspace check with diff-scope failed with exit code $EXIT_CODE"
    fi
fi
rm -rf "$WORKSPACE_DIR"

section "Testing baseline generation"
BASELINE_DIR=$(mktemp -d)
cat > "$BASELINE_DIR/Cargo.toml" << 'EOF'
[package]
name = "baseline-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "*"
EOF

BASELINE_OUT="$BASELINE_DIR/depguard.baseline.toml"
if "$DEPGUARD_BIN" --repo-root "$BASELINE_DIR" baseline --output "$BASELINE_OUT" > /dev/null 2>&1; then
    pass "Baseline generation works"
    if [[ -f "$BASELINE_OUT" ]]; then
        pass "Baseline file created: $BASELINE_OUT"
    else
        fail "Baseline file not created"
    fi
else
    info "Baseline generation may have failed (expected for some configurations)"
fi
rm -rf "$BASELINE_DIR"

section "Testing explain command"
# Test explain with check ID
if "$DEPGUARD_BIN" explain no_wildcards > /dev/null 2>&1; then
    pass "depguard explain no_wildcards works"
else
    fail "depguard explain no_wildcards failed"
fi

# Test explain with code
if "$DEPGUARD_BIN" explain wildcard_found > /dev/null 2>&1; then
    pass "depguard explain wildcard_found works"
else
    fail "depguard explain wildcard_found failed"
fi

section "Testing schema conformance"
# Test v2 report schema
if "$DEPGUARD_BIN" --repo-root "$TEMP_DIR" check --report-version v2 --report-out "$TEMP_DIR/v2-report.json" > /dev/null 2>&1; then
    pass "v2 report generation works"
    if command -v jq > /dev/null 2>&1; then
        SCHEMA_VERSION=$(jq -r '.schema // empty' "$TEMP_DIR/v2-report.json" 2>/dev/null || echo "")
        if [[ "$SCHEMA_VERSION" == "depguard.report.v2" ]]; then
            pass "v2 report has correct schema identifier"
        else
            info "v2 report schema version: $SCHEMA_VERSION"
        fi
    fi
else
    EXIT_CODE=$?
    if [[ $EXIT_CODE -eq 0 || $EXIT_CODE -eq 2 ]]; then
        pass "v2 report generation works (exit code $EXIT_CODE)"
    else
        fail "v2 report generation failed with exit code $EXIT_CODE"
    fi
fi

# Test sensor-v1 report schema
if "$DEPGUARD_BIN" --repo-root "$TEMP_DIR" check --report-version sensor-v1 --mode cockpit --report-out "$TEMP_DIR/sensor-report.json" > /dev/null 2>&1; then
    pass "sensor-v1 report generation works"
    if command -v jq > /dev/null 2>&1; then
        SCHEMA_VERSION=$(jq -r '.schema // empty' "$TEMP_DIR/sensor-report.json" 2>/dev/null || echo "")
        if [[ "$SCHEMA_VERSION" == "sensor.report.v1" ]]; then
            pass "sensor-v1 report has correct schema identifier"
        else
            info "sensor-v1 report schema version: $SCHEMA_VERSION"
        fi
    fi
else
    EXIT_CODE=$?
    if [[ $EXIT_CODE -eq 0 || $EXIT_CODE -eq 2 ]]; then
        pass "sensor-v1 report generation works (exit code $EXIT_CODE)"
    else
        fail "sensor-v1 report generation failed with exit code $EXIT_CODE"
    fi
fi

section "Testing workspace check"
# Test check on the actual workspace if available
if [[ -d "$REPO_ROOT/crates" ]]; then
    WORKSPACE_REPORT="$TEMP_DIR/workspace-report.json"
    if "$DEPGUARD_BIN" --repo-root "$REPO_ROOT" check --report-out "$WORKSPACE_REPORT" > /dev/null 2>&1; then
        pass "Workspace check on actual repo works"
    else
        EXIT_CODE=$?
        if [[ $EXIT_CODE -eq 0 || $EXIT_CODE -eq 2 ]]; then
            pass "Workspace check on actual repo works (exit code $EXIT_CODE)"
        else
            info "Workspace check on actual repo exited with code $EXIT_CODE (may be expected)"
        fi
    fi
else
    info "Skipping workspace check (no crates directory found)"
fi

echo ""
echo -e "${GREEN}All comprehensive smoke tests passed!${NC}"
exit 0
