# Comprehensive smoke test script for depguard (PowerShell)
# Generated by: cargo xtask generate-smoke
# Generated at: 2026-04-02T10:56:22Z
#
# This script verifies the depguard binary works with comprehensive operations.
# Exit codes: 0 = pass, 1 = fail

param(
    [string]$DepguardBin = ""
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Get-Item "$ScriptDir\..\..").FullName

if ([string]::IsNullOrEmpty($DepguardBin)) {
    $DepguardBin = Join-Path $RepoRoot "target\debug\depguard.exe"
}

function Write-Pass($message) {
    Write-Host "[PASS] $message" -ForegroundColor Green
}

function Write-Fail($message) {
    Write-Host "[FAIL] $message" -ForegroundColor Red
    exit 1
}

function Write-Info($message) {
    Write-Host "[INFO] $message" -ForegroundColor Yellow
}

function Write-Section($message) {
    Write-Host "=== $message ===" -ForegroundColor Blue
}

function New-TempDir {
    $tempPath = [System.IO.Path]::GetTempPath()
    $tempDir = Join-Path $tempPath "depguard-smoke-$(Get-Random)"
    New-Item -ItemType Directory -Path $tempDir | Out-Null
    return $tempDir
}

function Invoke-DepguardQuiet([string[]]$Arguments) {
    $stdoutPath = [System.IO.Path]::GetTempFileName()
    $stderrPath = [System.IO.Path]::GetTempFileName()
    try {
        $process = Start-Process -FilePath $DepguardBin -ArgumentList $Arguments -NoNewWindow -Wait -PassThru -RedirectStandardOutput $stdoutPath -RedirectStandardError $stderrPath
        return $process.ExitCode
    } finally {
        Remove-Item @($stdoutPath, $stderrPath) -Force -ErrorAction SilentlyContinue
    }
}

# Check binary exists
if (-not (Test-Path $DepguardBin)) {
    Write-Fail "Binary not found: $DepguardBin"
}
Write-Pass "Binary exists: $DepguardBin"

# Test --help
try {
    & $DepguardBin --help | Out-Null
    Write-Pass "depguard --help runs successfully"
} catch {
    Write-Fail "depguard --help failed: $_"
}

# Test --version
try {
    $versionOutput = & $DepguardBin --version 2>&1
    $firstVersionLine = (($versionOutput | Out-String).Trim() -split "\r?\n")[0]
    if ($versionOutput -match "depguard") {
        Write-Pass "depguard --version outputs version info: $firstVersionLine"
    } else {
        Write-Fail "depguard --version output unexpected: $versionOutput"
    }
} catch {
    Write-Fail "depguard --version failed: $_"
}

# Create a comprehensive test fixture
$TempDir = New-TempDir
try {
    $CargoToml = @"
[package]
name = "smoke-test-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
tokio = { version = "1.0", features = ["full"] }
regex = "*"

[dev-dependencies]
criterion = "0.5"
"@
    Set-Content -Path (Join-Path $TempDir "Cargo.toml") -Value $CargoToml -NoNewline

    Write-Section "Testing basic check command"
    
    # Test check command with minimal fixture
    $ReportOut = Join-Path $TempDir "report.json"
    $exitCode = 0
    try {
        & $DepguardBin --repo-root $TempDir check --report-out $ReportOut *> $null
        $exitCode = $LASTEXITCODE
    } catch {
        $exitCode = $_.Exception.HResult
    }
    
    if ($LASTEXITCODE -eq 0) {
        Write-Pass "depguard check runs on fixture"
    } elseif ($LASTEXITCODE -eq 2) {
        Write-Pass "depguard check runs (policy violation exit code 2 is acceptable)"
    } else {
        Write-Fail "depguard check failed with exit code $LASTEXITCODE"
    }

    # Verify report was created and is valid JSON
    if (Test-Path $ReportOut) {
        Write-Pass "Report file created: $ReportOut"
        try {
            Get-Content $ReportOut | ConvertFrom-Json | Out-Null
            Write-Pass "Report is valid JSON"
        } catch {
            Write-Fail "Report is not valid JSON: $_"
        }
    } else {
        Write-Fail "Report file not created"
    }

    Write-Section "Testing output formats"
    
    # Test markdown output
    $mdOutput = Join-Path $TempDir "output.md"
    try {
        & $DepguardBin md --report $ReportOut *> $mdOutput
        Write-Pass "Markdown output generation works"
    } catch {
        Write-Fail "Markdown output generation failed: $_"
    }

    # Test annotations output
    $annotationsOutput = Join-Path $TempDir "annotations.txt"
    try {
        & $DepguardBin annotations --report $ReportOut *> $annotationsOutput
        Write-Pass "Annotations output generation works"
    } catch {
        Write-Fail "Annotations output generation failed: $_"
    }

    # Test SARIF output
    $sarifOutput = Join-Path $TempDir "output.sarif"
    try {
        & $DepguardBin sarif --report $ReportOut *> $sarifOutput
        Write-Pass "SARIF output generation works"
        # Validate SARIF is valid JSON
        try {
            Get-Content $sarifOutput | ConvertFrom-Json | Out-Null
            Write-Pass "SARIF output is valid JSON"
        } catch {
            Write-Fail "SARIF output is not valid JSON: $_"
        }
    } catch {
        Write-Fail "SARIF output generation failed: $_"
    }

    # Test JUnit output
    $junitOutput = Join-Path $TempDir "output.junit"
    try {
        & $DepguardBin junit --report $ReportOut *> $junitOutput
        Write-Pass "JUnit output generation works"
    } catch {
        Write-Fail "JUnit output generation failed: $_"
    }

    # Test JSONL output
    $jsonlOutput = Join-Path $TempDir "output.jsonl"
    try {
        & $DepguardBin jsonl --report $ReportOut *> $jsonlOutput
        Write-Pass "JSONL output generation works"
    } catch {
        Write-Fail "JSONL output generation failed: $_"
    }

    Write-Section "Testing exit codes"
    
    # Test with a clean fixture (should exit 0)
    $CleanDir = New-TempDir
    try {
        $CleanToml = @"
[package]
name = "clean-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
"@
        Set-Content -Path (Join-Path $CleanDir "Cargo.toml") -Value $CleanToml -NoNewline
        
        $CleanReport = Join-Path $CleanDir "report.json"
        $exitCode = 0
        try {
            & $DepguardBin --repo-root $CleanDir check --report-out $CleanReport *> $null
            $exitCode = $LASTEXITCODE
        } catch {
            $exitCode = $_.Exception.HResult
        }
        
        if ($LASTEXITCODE -eq 0) {
            Write-Pass "Clean fixture exits with code 0"
        } else {
            Write-Fail "Clean fixture exited with code $LASTEXITCODE (expected 0)"
        }
    } finally {
        Remove-Item -Recurse -Force $CleanDir -ErrorAction SilentlyContinue
    }

    # Test with violations (should exit 2)
    $ViolationsDir = New-TempDir
    try {
        $ViolationsToml = @"
[package]
name = "violations-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "*"
tokio = "*"
"@
        Set-Content -Path (Join-Path $ViolationsDir "Cargo.toml") -Value $ViolationsToml -NoNewline
        
        $ViolationsReport = Join-Path $ViolationsDir "report.json"
        $exitCode = 0
        try {
            & $DepguardBin --repo-root $ViolationsDir check --report-out $ViolationsReport *> $null
            $exitCode = $LASTEXITCODE
        } catch {
            $exitCode = $_.Exception.HResult
        }
        
        if ($exitCode -eq 2) {
            Write-Pass "Violations fixture exits with code 2 (policy failure)"
        } elseif ($exitCode -eq 0) {
            Write-Fail "Violations fixture unexpectedly exited with code 0"
        } else {
            Write-Fail "Violations fixture exited with unexpected code $exitCode"
        }
    } finally {
        Remove-Item -Recurse -Force $ViolationsDir -ErrorAction SilentlyContinue
    }

    Write-Section "Testing diff-scope functionality"
    
    # Create a workspace for diff-scope testing
    $WorkspaceDir = New-TempDir
    try {
        $WorkspaceToml = @"
[workspace]
members = ["member1", "member2"]
"@
        Set-Content -Path (Join-Path $WorkspaceDir "Cargo.toml") -Value $WorkspaceToml -NoNewline
        
        $Member1Dir = Join-Path $WorkspaceDir "member1"
        New-Item -ItemType Directory -Path $Member1Dir | Out-Null
        $Member1Toml = @"
[package]
name = "member1"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
"@
        Set-Content -Path (Join-Path $Member1Dir "Cargo.toml") -Value $Member1Toml -NoNewline
        
        $Member2Dir = Join-Path $WorkspaceDir "member2"
        New-Item -ItemType Directory -Path $Member2Dir | Out-Null
        $Member2Toml = @"
[package]
name = "member2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.0"
"@
        Set-Content -Path (Join-Path $Member2Dir "Cargo.toml") -Value $Member2Toml -NoNewline
        
        $DiffReport = Join-Path $WorkspaceDir "report.json"
        $exitCode = 0
        try {
            & $DepguardBin --repo-root $WorkspaceDir check --report-out $DiffReport *> $null
            $exitCode = $LASTEXITCODE
        } catch {
            $exitCode = $_.Exception.HResult
        }
        
        if ($LASTEXITCODE -eq 0 -or $LASTEXITCODE -eq 2) {
            Write-Pass "Workspace check with diff-scope works (exit code $LASTEXITCODE)"
        } else {
            Write-Fail "Workspace check with diff-scope failed with exit code $LASTEXITCODE"
        }
    } finally {
        Remove-Item -Recurse -Force $WorkspaceDir -ErrorAction SilentlyContinue
    }

    Write-Section "Testing baseline generation"
    
    $BaselineDir = New-TempDir
    try {
        $BaselineToml = @"
[package]
name = "baseline-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "*"
"@
        Set-Content -Path (Join-Path $BaselineDir "Cargo.toml") -Value $BaselineToml -NoNewline
        
        $BaselineOut = Join-Path $BaselineDir "depguard.baseline.toml"
        $exitCode = Invoke-DepguardQuiet @("--repo-root", $BaselineDir, "baseline", "--output", $BaselineOut)

        if ($exitCode -ne 0) {
            Write-Fail "Baseline generation failed with exit code $exitCode"
        }

        Write-Pass "Baseline generation works"
        if (Test-Path $BaselineOut) {
            Write-Pass "Baseline file created: $BaselineOut"
        } else {
            Write-Fail "Baseline file not created"
        }
    } finally {
        Remove-Item -Recurse -Force $BaselineDir -ErrorAction SilentlyContinue
    }

    Write-Section "Testing explain command"
    
    # Test explain with check ID
    try {
        & $DepguardBin explain deps.no_wildcards *> $null
        Write-Pass "depguard explain deps.no_wildcards works"
    } catch {
        Write-Fail "depguard explain deps.no_wildcards failed: $_"
    }

    # Test explain with code
    try {
        & $DepguardBin explain wildcard_version *> $null
        Write-Pass "depguard explain wildcard_version works"
    } catch {
        Write-Fail "depguard explain wildcard_version failed: $_"
    }

    Write-Section "Testing schema conformance"
    
    # Test v2 report schema
    $v2Report = Join-Path $TempDir "v2-report.json"
    $exitCode = 0
    try {
        & $DepguardBin --repo-root $TempDir check --report-version v2 --report-out $v2Report *> $null
        $exitCode = $LASTEXITCODE
    } catch {
        $exitCode = $_.Exception.HResult
    }
    
    if ($exitCode -ne 0 -and $exitCode -ne 2) {
        Write-Fail "v2 report generation failed with exit code $exitCode"
    }

    if (-not (Test-Path $v2Report)) {
        Write-Fail "v2 report not created"
    }

    Write-Pass "v2 report generation works (exit code $exitCode)"
    try {
        $v2Content = Get-Content $v2Report | ConvertFrom-Json
        if ($v2Content.schema -eq "depguard.report.v2") {
            Write-Pass "v2 report has correct schema identifier"
        } else {
            Write-Fail "v2 report schema version mismatch: expected depguard.report.v2, got '$($v2Content.schema)'"
        }
    } catch {
        Write-Fail "Could not validate v2 report schema: $_"
    }

    # Test sensor-v1 report schema
    $sensorReport = Join-Path $TempDir "sensor-report.json"
    $exitCode = 0
    try {
        & $DepguardBin --repo-root $TempDir check --report-version sensor-v1 --mode cockpit --report-out $sensorReport *> $null
        $exitCode = $LASTEXITCODE
    } catch {
        $exitCode = $_.Exception.HResult
    }
    
    if ($exitCode -ne 0 -and $exitCode -ne 2) {
        Write-Fail "sensor-v1 report generation failed with exit code $exitCode"
    }

    if (-not (Test-Path $sensorReport)) {
        Write-Fail "sensor-v1 report not created"
    }

    Write-Pass "sensor-v1 report generation works (exit code $exitCode)"
    try {
        $sensorContent = Get-Content $sensorReport | ConvertFrom-Json
        if ($sensorContent.schema -eq "sensor.report.v1") {
            Write-Pass "sensor-v1 report has correct schema identifier"
        } else {
            Write-Fail "sensor-v1 report schema version mismatch: expected sensor.report.v1, got '$($sensorContent.schema)'"
        }
    } catch {
        Write-Fail "Could not validate sensor-v1 report schema: $_"
    }

    Write-Section "Testing workspace check"
    
    # Test check on actual workspace if available
    if (Test-Path (Join-Path $RepoRoot "crates")) {
        $WorkspaceReport = Join-Path $TempDir "workspace-report.json"
        $exitCode = 0
        try {
            & $DepguardBin --repo-root $RepoRoot check --report-out $WorkspaceReport *> $null
            $exitCode = $LASTEXITCODE
        } catch {
            $exitCode = $_.Exception.HResult
        }
        
        if ($LASTEXITCODE -eq 0 -or $LASTEXITCODE -eq 2) {
            Write-Pass "Workspace check on actual repo works (exit code $LASTEXITCODE)"
        } else {
            Write-Info "Workspace check on actual repo exited with code $LASTEXITCODE (may be expected)"
        }
    } else {
        Write-Info "Skipping workspace check (no crates directory found)"
    }

} finally {
    Remove-Item -Recurse -Force $TempDir -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "All comprehensive smoke tests passed!" -ForegroundColor Green
exit 0
