#!/usr/bin/env bash
# Smoke test script for depguard
# Generated by: cargo xtask generate-smoke
# Generated at: 2026-03-01T04:47:08Z
#
# This script verifies the depguard binary works with basic operations.
# Exit codes: 0 = pass, 1 = fail

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEPGUARD_BIN="${DEPGUARD_BIN:-$REPO_ROOT/target/debug/depguard}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

pass() {
    echo -e "${GREEN}✓${NC} $1"
}

fail() {
    echo -e "${RED}✗${NC} $1"
    exit 1
}

info() {
    echo -e "${YELLOW}ℹ${NC} $1"
}

# Check binary exists
if [[ ! -x "$DEPGUARD_BIN" ]]; then
    fail "Binary not found or not executable: $DEPGUARD_BIN"
fi
pass "Binary exists: $DEPGUARD_BIN"

# Test --help
if "$DEPGUARD_BIN" --help > /dev/null 2>&1; then
    pass "depguard --help runs successfully"
else
    fail "depguard --help failed"
fi

# Test --version
VERSION_OUTPUT=$("$DEPGUARD_BIN" --version 2>&1) || fail "depguard --version failed"
if [[ "$VERSION_OUTPUT" =~ depguard ]]; then
    pass "depguard --version outputs version info: $(echo "$VERSION_OUTPUT" | head -1)"
else
    fail "depguard --version output unexpected: $VERSION_OUTPUT"
fi

# Create a minimal test fixture
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

cat > "$TEMP_DIR/Cargo.toml" << 'EOF'
[package]
name = "smoke-test-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
EOF

# Test check command with minimal fixture
REPORT_OUT="$TEMP_DIR/report.json"
if "$DEPGUARD_BIN" --repo-root "$TEMP_DIR" check --report-out "$REPORT_OUT" > /dev/null 2>&1; then
    pass "depguard check runs on minimal fixture"
else
    # Check may exit 2 for policy violations, which is acceptable for smoke test
    EXIT_CODE=$?
    if [[ $EXIT_CODE -eq 2 ]]; then
        pass "depguard check runs (policy violation exit code 2 is acceptable)"
    else
        fail "depguard check failed with exit code $EXIT_CODE"
    fi
fi

# Verify report was created
if [[ -f "$REPORT_OUT" ]]; then
    pass "Report file created: $REPORT_OUT"
    # Validate it's valid JSON
    if command -v jq > /dev/null 2>&1; then
        if jq empty "$REPORT_OUT" 2>/dev/null; then
            pass "Report is valid JSON"
        else
            fail "Report is not valid JSON"
        fi
    else
        info "jq not available, skipping JSON validation"
    fi
else
    info "Report file not created (may be expected for some modes)"
fi

# Test explain command
if "$DEPGUARD_BIN" explain no_wildcards > /dev/null 2>&1; then
    pass "depguard explain runs successfully"
else
    fail "depguard explain failed"
fi

echo ""
echo -e "${GREEN}All smoke tests passed!${NC}"
exit 0
